# Notes

This first notebook will be basically to have some notes as a reminder of the basic tools.

### Numpy

In [1]:
import numpy as np

#### One-Dimensional Array

In [2]:
# One-dimensional array
arr1D = np.array([1, 2, 3, 4, 5])
arr1D

array([1, 2, 3, 4, 5])

In [19]:
arr1D_float = np.array([1.5, 2.2, 3.1, 4.6, 5.9], dtype=np.float64)  # we could make them floats
print(arr1D_float, arr1D_float.dtype)

[1. 2. 3. 4. 5.] float64


In [21]:
arr1D_bool = np.array([0, 1, 0, 1], dtype=np.bool)  # we could make them boolean
print(arr1D_bool, arr1D_bool.dtype)

[False  True False  True] bool


/tmp/ipykernel_1622542/4084439031.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1D_bool = np.array([0, 1, 0, 1], dtype=np.bool)  # we could make them boolean


In [22]:
# We could also convert the dtype of the first array we created, arr1D
arr1D.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [24]:
# The same for converting the _float to _int
arr1D_float.astype(np.int64)  # We see that it truncates those values

array([1, 2, 3, 4, 5])

In [14]:
np.arange(6)  # could also use arange

array([0, 1, 2, 3, 4, 5])

#### Two-Dimensional Array

In [4]:
# Two-dimensional array
arr2D = np.array([[1, 2], [3, 4]])
arr2D

array([[1, 2],
       [3, 4]])

In [15]:
np.random.randn(2, 2)  # 2 * 2 matrix of random normal values with mean 0 and std 1

array([[ 0.67705403,  0.31831011],
       [-0.69972465, -0.62492317]])

#### N-Dimensional Array

In [6]:
# N-dimensional arrays
arr4D = np.array(range(16)).reshape((2, 2, 2, 2))
arr4D

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [10]:
# Array of zeros (rows * columns)
np.zeros(shape=(2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# Array of ones
np.ones(shape=(2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# Identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Indexing Values

In [26]:
rand_array = np.random.randn(2, 2)
rand_array

array([[ 0.08651102,  0.59245191],
       [-0.47987871, -0.13545191]])

In [29]:
# We access: [row, column]
print(rand_array[0,0], rand_array[0,1])

0.0865110156455437 0.5924519138553017


In [36]:
# We could also do slicing
print("Collect all values in the second row:", rand_array[1:])

print("Collect all values in the first row, from column 1:")
rand_array[0:, 1:]

Collect all values in the second row: [[-0.47987871 -0.13545191]]
Collect all values in the first row, from column 1:


array([[ 0.59245191],
       [-0.13545191]])

In [37]:
print("Get last row and last column:", rand_array[-1, -1])

Get last row and last column: -0.1354519146353539


In [41]:
print("Get everything:")
rand_array[:]

Get everything:


array([[ 0.08651102,  0.59245191],
       [-0.47987871, -0.13545191]])

- TODO: Numpy Notes p.55 - 72

- TODO: Pandas Notes p.74 - 109

- TODO: Matplotlib Notes p.111 - 144